export const REQUEST_CHARACTERS = 'REQUEST_CHARACTERS';
export const RECEIVE_CHARACTERS_SUCCESS = 'RECEIVE_CHARACTERS_SUCCESS';
export const RECEIVE_CHARACTERS_ERROR = 'RECEIVE_CHARACTERS_ERROR';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
